SIM = questa
TOPLEVEL_LANG = verilog

VERILOG_SOURCES += $(PWD)/sim_top.sv
#VERILOG_SOURCES += ../rtl/top.sv
#VERILOG_SOURCES += ../rtl/uart/uart_tx.sv
#VERILOG_SOURCES += ../rtl/uart/uart_rx.sv

TOPLEVEL = sim_top

MODULE = test

include $(shell cocotb-config --makefiles)/Makefile.sim
